name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: rperezsoto
  GITHUB_REPOSITORY: rperezsoto/my-recommended-sources
  GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}

on: 
  push:
    branches: [ master ]


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
        run: |
          set -x
          apt-get update
          apt-get install -y git
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
        run: |
          git checkout -b gh-pages
          find ./parent -mindepth 1 -name four -prune -o -exec rm -rf {} \;
          cd docs
          apt-get install python3
          python3 -m pip install -r requirements.txt
          make html
          mv build/html ../..
          rm -r docs
          git push origin gh-pages
        shell: bash
